### ISSUE TITLE
萤石CS-XP1 摄像头使用该sdk无法配网

### ISSUE THREAD

**Issue by pipihu** [Ezviz-Open/EZConfigWifiSDK#1]
型号: CS-XP1(3MP , H.265)
配网SDK版本: 6.3.1.20200429
使用这个配网sdk无法对xp1摄像头配网, smartconfig模式和声波模式都不行,错误信息都是超时.
尝试过对C6HC和C6H配网都没有任何问题,只有xp1不行.

错误提示: ***error code is: 15,error msg is: config wifi timeout, default timeout is90s
![001](https://user-images.githubusercontent.com/3360808/100840068-4ca98a80-34b0-11eb-8391-8086891efc16.jpg)
![002](https://user-images.githubusercontent.com/3360808/100840072-4f0be480-34b0-11eb-9c0f-426791524d6c.jpg)

**Comment by huangzhuhua666** [comment]
我CS-C6CN也陪不了

**Comment by pipihu** [comment]
xp1 这个问题我已经在萤石开放平台提交工单了,12月4号的答复是安排研发人员排查定位问题.
配网这事儿真的挺头疼的.萤石的产品无非就是,二维码（早期的c6h用这个，目前看来是淘汰了）、声波、Smart配网、AP配网。
现在新出的产品感觉就是在后三种配网模式中随意搭配的，但设备具体支持哪种，官网的产品参数中并没有明确标注，甚至连http接口中的能力集查询（https://open.ys7.com/doc/zh/book/index/capacity.html#device_capacity）查到的结果都不一定准确（xp1查询设备能力集是支持smart配网的，实际上不行）。
只能拿到设备用配网sdk进行几种配网尝试来判断。
今天偶然发现xp1摄像头在重置之后默认是开启AP模式的，用sdkdemo试了下ap模式能配网成功。只能暂时先用这个了。

**Comment by pipihu** [comment]
> 我CS-C6CN也陪不了

c6cn，我们这边的供应商没货我拿不到样机，不清楚具体情况。目前我能买到的只有xp1

**Comment by huangzhuhua666** [comment]
但是用萤石云视频的app配又成功。。

**Comment by pipihu** [comment]
XP1也是如此，萤石云视频App也能给xp1配网成功，我想它用的是AP模式。
萤石云视频App是根据序列号判断设备型号来自动选择对应配网方式的。
问题就出在这里，每个型号的设备具体支持什么配网方式官网没标明，能力集查到的也不一定准确。只能拿设备来测试。
如果你的c6cn和xp1一样，重置之后能用手机搜到一个SSID为 “EZVIZ_设备序列号”  这样的wifi信号，那就是AP模式，这个ap的密码是 “EZVIZ_设备验证码”。
参照sdkdemo做用ap模式配网即可

**Comment by huangzhuhua666** [comment]
> XP1也是如此，萤石云视频App也能给xp1配网成功，我想它用的是AP模式。
> 萤石云视频App是根据序列号判断设备型号来自动选择对应配网方式的。
> 问题就出在这里，每个型号的设备具体支持什么配网方式官网没标明，能力集查到的也不一定准确。只能拿设备来测试。
> 如果你的c6cn和xp1一样，重置之后能用手机搜到一个SSID为 “EZVIZ_设备序列号” 这样的wifi信号，那就是AP模式，这个ap的密码是 “EZVIZ_设备验证码”。
> 参照sdkdemo做用ap模式配网即可

确实用ap模式可以配置，谢了
